lib/global_reader_web/router.ex
defmodule GlobalReaderWeb.Router do
  use GlobalReaderWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GlobalReaderWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GlobalReaderWeb do
    pipe_through :browser

    get "/", IndexController, :index

    scope "/users", UserLive do
      live "/new", New, :new
      live "/:email", Show, :show
    end

    scope "/sessions", SessionLive do
      live "/new", New, :new
    end

    scope "/password_resets", PasswordResetLive do
      live "/new", New, :new
      live "/:uuid", Edit, :edit
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", GlobalReaderWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GlobalReaderWeb.Telemetry
    end
  end
end

lib/global_reader_web/templates/index/index.html.eex
<h2>Homework app for GlobalReader</h2>

<ol>
    <li><%= link "Create user", to: Routes.user_new_path(@conn, :new) %></li>
    <li><%= link "Sign in", to: Routes.session_new_path(@conn, :new) %></li>
    <li><%= link "Reset password", to: Routes.password_reset_new_path(@conn, :new) %></li>
    <li>Click link in email</li>
    <li>Set new password</li>
</ol>